### ISSUE TITLE
Data over audio

### ISSUE THREAD

**Issue by nicolas-f** [OpenAcousticDevices/AudioMoth-Chime#1]
I can't find any reference for this project.

If you still have to do the C code for the decoding on the audio data maybe you could study the QRTone open-source solution?

It run well on Arduino nano 33 ble sense (48 Mhz)

The source code is here:

https://github.com/Ifsttar/qrtone

There is Android demo client:
https://github.com/Ifsttar/qrtone-android

There is also a javascript/html code:
https://ifsttar.github.io/qrtone/

Some videos:
https://twitter.com/qrtone

**Comment by pcprince** [comment]
Hi Nicholas,

We have firmware for decoding the audio produced by this library currently in testing. It'll be included in the imminent 1.5.0 firmware release.
